### ISSUE TITLE
After submission: See status & See logs

### ISSUE THREAD

**Issue by Katzhb** [cpswarm/deployment-tool-ui#6]
- [x] generate the status tree
   generate tree after submit deployment and click the tree view in the deployment card is different. Reason: the logs is not from 0.
- [x] click tree node, show node logs

**Comment by farshidtz** [comment]
Done with https://github.com/cpswarm/deployment-tool/issues/7

Added some info to wiki: https://github.com/cpswarm/deployment-tool/wiki/Events

Sample code for subscribing to events: https://github.com/cpswarm/deployment-tool/blob/master/ui/events.html
